
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'menu': 'Menu',
    'home': 'Home',
    'admin_panel': 'Admin Panel',
    'all_categories': 'All Categories',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'my_orders': 'My Orders',
    'account': 'Account',
    'follow_us': 'Follow Us',
    'language': 'Language',
    'english': 'English',
    'bangla': 'বাংলা',
    'cart': 'Cart',
    'category': 'Category',
    'whatsapp': 'WhatsApp',
    'updates': 'Updates',
    'welcome': 'Welcome to MY shopBD!',
    'explore': 'Explore the best products directly curated for you.',
    'just_now': 'Just now',
    'search': 'Search anything on MY shopBD...',
    'buy_now': 'Buy Now',
    'add_to_cart': 'Add to Cart',
    'in_cart': 'In Cart',
    'description': 'Description',
    'order_policy': 'Order Policy',
    'reviews': 'Reviews',
    'authentic': 'Authentic',
    'fast_delivery': 'Fast Delivery',
    'return_policy': '7 Days Return',
    'off': 'OFF',
    'remove_from_cart': 'Remove from Cart',
    'cart_empty': 'Your cart is empty',
    'cart_empty_desc': "Looks like you haven't added anything yet.",
    'start_shopping': 'Start Shopping',
    'my_cart': 'My Shopping Cart',
    'subtotal': 'Subtotal',
    'delivery': 'Delivery',
    'calc_at_checkout': 'CALCULATED AT CHECKOUT',
    'total': 'Total',
    'checkout_now': 'Checkout Now',
    'checkout': 'Checkout',
    'back_to_cart': 'Back to Cart',
    'shipping_details': 'Shipping Details',
    'new_address': 'New Address',
    'use_saved': 'Use Saved',
    'full_name': 'Full Name',
    'mobile_number': 'Mobile Number',
    'district': 'District (Jela)',
    'thana': 'Thana / Upazila',
    'address_details': 'Address Details',
    'select_district': 'Select District',
    'select_thana': 'Select Thana',
    'street_area': 'Street, area, etc.',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'payment_notice': 'Please complete the payment to our official number after confirming the order. Our team will contact you for the transaction ID.',
    'order_summary': 'Order Summary',
    'shipping_charge': 'Shipping Charge',
    'select_address': 'Select Address',
    'total_payable': 'Total Payable',
    'confirm_order': 'CONFIRM ORDER',
    'order_confirmed': 'Order Confirmed!',
    'order_success_desc': 'Your order has been placed successfully. Thank you for shopping with MY shopBD.',
    'redirecting_orders': 'Redirecting to your orders...',
    'shop_by_category': 'Shop by Category',
    'explore_collection': 'Explore Collection',
    'categories': 'Categories',
    'order_history': 'Order History',
    'sign_in_orders': 'Sign in to see orders',
    'track_history': 'Track your sourcing history by logging in.',
    'go_to_profile': 'Go to Profile',
    'order_id': 'Order #',
    'delivery_details': 'Delivery Details',
    'method': 'Method',
    'items_count': 'Items',
    'no_orders': 'No orders yet',
    'no_orders_desc': 'When you buy something, your orders will appear here.',
    'start_sourcing': 'Start Sourcing',
    'pending': 'Pending',
    'delivered': 'Delivered',
    'profile': 'Profile',
    'my_account': 'MY shopBD Account',
    'direct_sourcing': 'Direct Sourcing & Secure Access',
    'login': 'Login',
    'signup': 'Signup',
    'gmail_address': 'Gmail Address',
    'send_code': 'Send Code',
    'change': 'Change',
    'verification_code': 'Gmail Verification Code',
    'resend': 'RESEND',
    'password': 'Password',
    'forgot_password': 'Forgot Password?',
    'secure_login': 'Secure Login',
    'verify_create': 'Verify & Create Account',
    'create_account': 'Create Account',
    'check_inbox': 'Check your Gmail inbox for the code',
    'trusted_network': 'Secure & Trusted Sourcing Network',
    'connect_with': 'Connect with',
    'edit_profile': 'Edit Profile',
    'activity_settings': 'Activity & Settings',
    'personal_info': 'Personal Information',
    'delivery_addresses': 'Delivery Addresses',
    'store_settings': 'Store Settings',
    'sign_out': 'Secure Sign Out',
    'update_profile': 'Update Profile',
    'tap_to_change': 'Tap image to change',
    'display_name': 'Display Name',
    'avatar_url': 'Avatar URL (Optional)',
    'save_changes': 'Save Changes',
    'shipments': 'Shipments',
    'locations': 'Locations',
    'admin_dashboard': 'Admin Dashboard',
    'store_management': 'Store Management System',
    'total_sales': 'Total Sales',
    'inventory': 'Inventory',
    'quick_action': 'Quick Action',
    'add_trending_desc': 'Add a new trending product to the store immediately.',
    'go_to_inventory': 'Go to Inventory',
    'store_inventory': 'Store Inventory',
    'categories_list': 'Categories List',
    'in_stock': 'In Stock',
    'out_of_stock': 'Out',
    'edit': 'Edit',
    'delete': 'Delete',
    'products': 'Products',
    'dashboard': 'Dashboard',
    'admin_access_required': 'Admin Access Required',
    'admin_access_required_desc': 'Please log in with administrator credentials to manage the store.',
    'go_to_admin_login': 'Go to Admin Login',
    'back_to_home': 'Back to Home',
    'delivery_settings': 'Delivery Settings',
    'dhaka_charge': 'Dhaka Charge',
    'bogura_charge': 'Bogura Charge',
    'other_charge': 'Other (Default)',
    'update_shipping_rates': 'Update Shipping Rates',
    'social_media_links': 'Social Media Links',
    'facebook_page_link': 'Facebook Page Link',
    'youtube_channel_link': 'YouTube Channel Link',
    'tiktok_profile_link': 'TikTok Profile Link',
    'site_visibility': 'Site Visibility',
    'promo_banner': 'Promo Banner',
    'dark_mode_default': 'Dark Mode Default',
    'security_account': 'Security & Account',
    'admin_username': 'Admin Username',
    'admin_password': 'Admin Password',
    'update_credentials': 'Update Credentials',
    'view_current_credentials': 'View Current Credentials',
    'home_banner_management': 'Home Banner Management',
    'global_order_policy': 'Global Order Policy',
    'banner_image_url': 'Banner Image URL',
    'update': 'Update',
    'add_new_product': 'Add New Product',
    'edit_product': 'Edit Product',
    'product_name': 'Product Name',
    'price': 'Price',
    'mark_in_stock': 'Mark as In-Stock',
    'product_description': 'Product Description',
    'product_image': 'Product Image',
    'upload_image': 'Upload Image',
    'save_product_changes': 'Save Product Changes',
    'add_category': 'Add Category',
    'category_name': 'Category Name',
    'add_new_category': 'Add New Category',
    'edit_category': 'Edit Category',
    'update_category_name': 'Update Category Name',
    'admin_credentials': 'Admin Credentials',
    'username': 'Username',
    'close': 'Close',
    'save': 'Save',
    'category_update_warning': 'Changing this will update all products currently in this category.',
    'credentials_safety_warning': 'Please keep these credentials safe and do not share them with anyone.',
    'show': 'Show',
    'hide': 'Hide',
    'whatsapp_updated': 'WhatsApp number updated successfully!',
    'shipping_rates_updated': 'Shipping rates updated successfully!',
    'facebook_link_updated': 'Facebook link updated!',
    'youtube_link_updated': 'YouTube link updated!',
    'tiktok_link_updated': 'TikTok link updated!',
    'admin_credentials_updated': 'Admin credentials updated successfully!',
    'empty_credentials_error': 'Username and Password cannot be empty.',
    'banner_updated': 'Banner image updated successfully!',
    'product_name_placeholder': 'e.g. Premium Sports Shoes',
    'product_desc_placeholder': 'Enter product details...',
    'order_policy_placeholder': 'Enter order policy details...',
    'no_image': 'No Image',
    'image_url_placeholder': 'Or paste image URL here...',
    'image_upload_hint': 'Upload a file or paste a direct link for the product image.',
    'category_name_placeholder': 'e.g. New Collection',
    'enter_new_name': 'Enter new name',
    'tracking_settings': 'Tracking Settings',
    'fb_pixel_id': 'Facebook Pixel ID',
    'fb_capi_token': 'Facebook CAPI Token',
    'fb_test_event_code': 'Facebook Test Event Code',
    'tiktok_pixel_id': 'TikTok Pixel ID',
    'gtm_id': 'Google Tag Manager ID',
    'ga4_id': 'Google Analytics 4 ID',
    'custom_scripts': 'Custom Scripts (Header)',
    'update_tracking': 'Update Tracking Config',
    'tracking_updated': 'Tracking configuration updated successfully!',
    'write_review': 'Write a Review',
    'write_review_placeholder': 'Share your experience with this product...',
    'send_review': 'Send Review',
    'review_sent_success': 'Thank you! Your review has been submitted for moderation.',
    'visit_live_dashboard': 'Visit Live Dashboard',
    'product_sizes': 'Product Sizes',
    'product_sizes_placeholder': 'e.g. S, M, L, XL (comma separated)',
    'select_size': 'Select Size',
    'api_settings': 'API Settings',
    'change_api_key': 'Change API Key',
    'api_key_notice': 'This key is used for AI features like smart descriptions and search recommendations.',
    'custom_api_key': 'Custom API Key',
    'save_api_key': 'Save API Key',
    'api_key_saved': 'API Key saved successfully!',
    'twelvedata_api_key': 'Twelvedata API Key',
  },
  bn: {
    'menu': 'মেনু',
    'home': 'হোম',
    'admin_panel': 'অ্যাডমিন প্যানেল',
    'all_categories': 'সব ক্যাটাগরি',
    'light_mode': 'লাইট মোড',
    'dark_mode': 'ডার্ক মোড',
    'my_orders': 'আমার অর্ডার',
    'account': 'অ্যাকাউন্ট',
    'follow_us': 'আমাদের অনুসরণ করুন',
    'language': 'ভাষা',
    'english': 'English',
    'bangla': 'বাংলা',
    'cart': 'কার্ট',
    'category': 'ক্যাটাগরি',
    'whatsapp': 'হোয়াটসঅ্যাপ',
    'updates': 'আপডেট',
    'welcome': 'মাই শপবিডিতে স্বাগতম!',
    'explore': 'আপনার জন্য সেরা পণ্যগুলো এখানে খুঁজুন।',
    'just_now': 'এইমাত্র',
    'search': 'MY shopBD-এ কিছু খুঁজুন...',
    'buy_now': 'এখনই কিনুন',
    'add_to_cart': 'কার্টে যোগ করুন',
    'in_cart': 'কার্টে আছে',
    'description': 'বর্ণনা',
    'order_policy': 'অর্ডার পলিসি',
    'reviews': 'রিভিউ',
    'authentic': 'আসল পণ্য',
    'fast_delivery': 'দ্রুত ডেলিভারি',
    'return_policy': '৭ দিনের রিটার্ন',
    'off': 'ছাড়',
    'remove_from_cart': 'কার্ট থেকে সরান',
    'cart_empty': 'আপনার কার্ট খালি',
    'cart_empty_desc': 'মনে হচ্ছে আপনি এখনও কিছু যোগ করেননি।',
    'start_shopping': 'কেনাকাটা শুরু করুন',
    'my_cart': 'আমার শপিং কার্ট',
    'subtotal': 'সাবটোটাল',
    'delivery': 'ডেলিভারি',
    'calc_at_checkout': 'চেকআউটে গণনা করা হবে',
    'total': 'মোট',
    'checkout_now': 'এখনই চেকআউট করুন',
    'checkout': 'চেকআউট',
    'back_to_cart': 'কার্টে ফিরে যান',
    'shipping_details': 'শিপিং বিবরণ',
    'new_address': 'নতুন ঠিকানা',
    'use_saved': 'সংরক্ষিত ব্যবহার করুন',
    'full_name': 'পুরো নাম',
    'mobile_number': 'মোবাইল নম্বর',
    'district': 'জেলা',
    'thana': 'থানা / উপজেলা',
    'address_details': 'ঠিকানার বিবরণ',
    'select_district': 'জেলা নির্বাচন করুন',
    'select_thana': 'থানা নির্বাচন করুন',
    'street_area': 'রাস্তা, এলাকা ইত্যাদি',
    'payment_method': 'পেমেন্ট পদ্ধতি',
    'cash': 'নগদ',
    'payment_notice': 'অর্ডার নিশ্চিত করার পর আমাদের অফিসিয়াল নম্বরে পেমেন্ট সম্পন্ন করুন। আমাদের টিম ট্রানজ্যাকশন আইডি-র জন্য আপনার সাথে যোগাযোগ করবে।',
    'order_summary': 'অর্ডারের সারাংশ',
    'shipping_charge': 'শিপিং চার্জ',
    'select_address': 'ঠিকানা নির্বাচন করুন',
    'total_payable': 'মোট প্রদেয়',
    'confirm_order': 'অর্ডার নিশ্চিত করুন',
    'order_confirmed': 'অর্ডার নিশ্চিত হয়েছে!',
    'order_success_desc': 'আপনার অর্ডার সফলভাবে সম্পন্ন হয়েছে। MY shopBD-এর সাথে কেনাকাটা করার জন্য ধন্যবাদ।',
    'redirecting_orders': 'আপনার অর্ডারে রিডাইরেক্ট করা হচ্ছে...',
    'shop_by_category': 'ক্যাটাগরি অনুযায়ী কিনুন',
    'explore_collection': 'সংগ্রহ দেখুন',
    'categories': 'ক্যাটাগরি',
    'order_history': 'অর্ডারের ইতিহাস',
    'sign_in_orders': 'অর্ডার দেখতে লগইন করুন',
    'track_history': 'লগইন করে আপনার কেনাকাটার ইতিহাস ট্র্যাক করুন।',
    'go_to_profile': 'প্রোফাইলে যান',
    'order_id': 'অর্ডার #',
    'delivery_details': 'ডেলিভারি বিবরণ',
    'method': 'পদ্ধতি',
    'items_count': 'আইটেম',
    'no_orders': 'এখনও কোনো অর্ডার নেই',
    'no_orders_desc': 'আপনি যখন কিছু কিনবেন, আপনার অর্ডার এখানে প্রদর্শিত হবে।',
    'start_sourcing': 'কেনাকাটা শুরু করুন',
    'pending': 'পেন্ডিং',
    'delivered': 'ডেলিভারি হয়েছে',
    'profile': 'প্রোফাইল',
    'my_account': 'MY shopBD অ্যাকাউন্ট',
    'direct_sourcing': 'সরাসরি সোর্সিং এবং নিরাপদ অ্যাক্সেস',
    'login': 'লগইন',
    'signup': 'সাইনআপ',
    'gmail_address': 'জিমেইল ঠিকানা',
    'send_code': 'কোড পাঠান',
    'change': 'পরিবর্তন',
    'verification_code': 'জিমেইল ভেরিফিকেশন কোড',
    'resend': 'পুনরায় পাঠান',
    'password': 'পাসওয়ার্ড',
    'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
    'secure_login': 'নিরাপদ লগইন',
    'verify_create': 'ভেরিফাই এবং অ্যাকাউন্ট তৈরি করুন',
    'create_account': 'অ্যাকাউন্ট তৈরি করুন',
    'check_inbox': 'কোডের জন্য আপনার জিমেইল ইনবক্স চেক করুন',
    'trusted_network': 'নিরাপদ এবং বিশ্বস্ত সোর্সিং নেটওয়ার্ক',
    'connect_with': 'এর সাথে সংযোগ করুন',
    'edit_profile': 'প্রোফাইল এডিট করুন',
    'activity_settings': 'অ্যাক্টিভিটি এবং সেটিংস',
    'personal_info': 'ব্যক্তিগত তথ্য',
    'delivery_addresses': 'ডেলিভারি ঠিকানা',
    'store_settings': 'স্টোর সেটিংস',
    'sign_out': 'নিরাপদ সাইন আউট',
    'update_profile': 'প্রোফাইল আপডেট করুন',
    'tap_to_change': 'ছবি পরিবর্তন করতে ট্যাপ করুন',
    'display_name': 'প্রদর্শন নাম',
    'avatar_url': 'অ্যাভাটার ইউআরএল (ঐচ্ছিক)',
    'save_changes': 'পরিবর্তন সংরক্ষণ করুন',
    'shipments': 'শিপমেন্ট',
    'locations': 'লোকেশন',
    'admin_dashboard': 'অ্যাডমিন ড্যাশবোর্ড',
    'store_management': 'স্টোর ম্যানেজমেন্ট সিস্টেম',
    'total_sales': 'মোট বিক্রয়',
    'inventory': 'ইনভেন্টরি',
    'quick_action': 'দ্রুত অ্যাকশন',
    'add_trending_desc': 'অবিলম্বে স্টোরে একটি নতুন ট্রেন্ডিং পণ্য যোগ করুন।',
    'go_to_inventory': 'ইনভেন্টরিতে যান',
    'store_inventory': 'স্টোর ইনভেন্টরি',
    'categories_list': 'ক্যাটাগরি তালিকা',
    'in_stock': 'স্টকে আছে',
    'out_of_stock': 'শেষ',
    'edit': 'এডিট',
    'delete': 'ডিলিট',
    'products': 'পণ্য',
    'dashboard': 'ড্যাশবোর্ড',
    'admin_access_required': 'অ্যাডমিন অ্যাক্সেস প্রয়োজন',
    'admin_access_required_desc': 'স্টোর পরিচালনা করতে দয়া করে অ্যাডমিন ক্রেডেনশিয়াল দিয়ে লগ ইন করুন।',
    'go_to_admin_login': 'অ্যাডমিন লগইনে যান',
    'back_to_home': 'হোমে ফিরে যান',
    'delivery_settings': 'ডেলিভারি সেটিংস',
    'dhaka_charge': 'ঢাকা চার্জ',
    'bogura_charge': 'বগুড়া চার্জ',
    'other_charge': 'অন্যান্য (ডিফল্ট)',
    'update_shipping_rates': 'শিপিং রেট আপডেট করুন',
    'social_media_links': 'সোশ্যাল মিডিয়া লিঙ্ক',
    'facebook_page_link': 'ফেসবুক পেজ লিঙ্ক',
    'youtube_channel_link': 'ইউটিউব চ্যানেল লিঙ্ক',
    'tiktok_profile_link': 'টিকটক প্রোফাইল লিঙ্ক',
    'site_visibility': 'সাইট ভিজিবিলিটি',
    'promo_banner': 'প্রোমো ব্যানার',
    'dark_mode_default': 'ডার্ক মোড ডিফল্ট',
    'security_account': 'সিকিউরিটি ও অ্যাকাউন্ট',
    'admin_username': 'অ্যাডমিন ইউজারনেম',
    'admin_password': 'অ্যাডমিন পাসওয়ার্ড',
    'update_credentials': 'ক্রেডেনশিয়াল আপডেট করুন',
    'view_current_credentials': 'বর্তমান ক্রেডেনশিয়াল দেখুন',
    'home_banner_management': 'হোম ব্যানার ম্যানেজমেন্ট',
    'global_order_policy': 'গ্লোবাল অর্ডার পলিসি',
    'banner_image_url': 'ব্যানার ইমেজ ইউআরএল',
    'update': 'আপডেট',
    'add_new_product': 'নতুন পণ্য যোগ করুন',
    'edit_product': 'পণ্য এডিট করুন',
    'product_name': 'পণ্যের নাম',
    'price': 'মূল্য',
    'mark_in_stock': 'স্টকে আছে হিসেবে চিহ্নিত করুন',
    'product_description': 'পণ্যের বর্ণনা',
    'product_image': 'পণ্যের ছবি',
    'upload_image': 'ছবি আপলোড করুন',
    'save_product_changes': 'পণ্যের পরিবর্তন সংরক্ষণ করুন',
    'add_category': 'ক্যাটাগরি যোগ করুন',
    'category_name': 'ক্যাটাগরির নাম',
    'add_new_category': 'নতুন ক্যাটাগরি যোগ করুন',
    'edit_category': 'ক্যাটাগরি এডিট করুন',
    'update_category_name': 'ক্যাটাগরির নাম আপডেট করুন',
    'admin_credentials': 'অ্যাডমিন ক্রেডেনশিয়াল',
    'username': 'ইউজারনেম',
    'close': 'বন্ধ করুন',
    'save': 'সংরক্ষণ করুন',
    'category_update_warning': 'এটি পরিবর্তন করলে এই ক্যাটাগরির অন্তর্ভুক্ত সব পণ্য আপডেট হবে।',
    'credentials_safety_warning': 'দয়া করে এই ক্রেডেনশিয়ালগুলো নিরাপদ রাখুন এবং কারো সাথে শেয়ার করবেন না।',
    'show': 'দেখুন',
    'hide': 'লুকান',
    'whatsapp_updated': 'হোয়াটসঅ্যাপ নম্বর সফলভাবে আপডেট হয়েছে!',
    'shipping_rates_updated': 'শিপিং রেট সফলভাবে আপডেট হয়েছে!',
    'facebook_link_updated': 'ফেসবুক লিঙ্ক আপডেট হয়েছে!',
    'youtube_link_updated': 'ইউটিউব লিঙ্ক আপডেট হয়েছে!',
    'tiktok_link_updated': 'টিকটক লিঙ্ক আপডেট হয়েছে!',
    'admin_credentials_updated': 'অ্যাডমিন ক্রেডেনশিয়াল সফলভাবে আপডেট হয়েছে!',
    'empty_credentials_error': 'ইউজারনেম এবং পাসওয়ার্ড খালি রাখা যাবে না।',
    'banner_updated': 'ব্যানার ইমেজ সফলভাবে আপডেট হয়েছে!',
    'product_name_placeholder': 'উদা: প্রিমিয়াম স্পোর্টস জুতো',
    'product_desc_placeholder': 'পণ্যের বিবরণ লিখুন...',
    'order_policy_placeholder': 'অর্ডার পলিসি বিবরণ লিখুন...',
    'no_image': 'কোনো ছবি নেই',
    'image_url_placeholder': 'অথবা ছবির ইউআরএল এখানে পেস্ট করুন...',
    'image_upload_hint': 'পণ্যের ছবির জন্য একটি ফাইল আপলোড করুন অথবা সরাসরি লিঙ্ক পেস্ট করুন।',
    'category_name_placeholder': 'উদা: নতুন কালেকশন',
    'enter_new_name': 'নতুন নাম লিখুন',
    'tracking_settings': 'ট্র্যাকিং সেটিংস',
    'fb_pixel_id': 'ফেসবুক পিক্সেল আইডি',
    'fb_capi_token': 'ফেসবুক CAPI টোকেন',
    'fb_test_event_code': 'ফেসবুক টেস্ট ইভেন্ট কোড',
    'tiktok_pixel_id': 'টিকটক পিক্সেল আইডি',
    'gtm_id': 'গুগল ট্যাগ ম্যানেজার আইডি',
    'ga4_id': 'গুগল অ্যানালিটিক্স ৪ আইডি',
    'custom_scripts': 'কাস্টম স্ক্রিপ্ট (হেডার)',
    'update_tracking': 'ট্র্যাকিং কনফিগ আপডেট করুন',
    'tracking_updated': 'ট্র্যাকিং কনফিগারেশন সফলভাবে আপডেট হয়েছে!',
    'write_review': 'একটি রিভিউ লিখুন',
    'write_review_placeholder': 'এই পণ্য সম্পর্কে আপনার অভিজ্ঞতা শেয়ার করুন...',
    'send_review': 'রিভিউ পাঠান',
    'review_sent_success': 'ধন্যবাদ! আপনার রিভিউটি মডারেশনের জন্য জমা দেওয়া হয়েছে।',
    'visit_live_dashboard': 'লাইভ ড্যাশবোর্ড ভিজিট করুন',
    'product_sizes': 'পণ্যের সাইজ',
    'product_sizes_placeholder': 'যেমন: S, M, L, XL (কমা দিয়ে আলাদা করুন)',
    'select_size': 'সাইজ নির্বাচন করুন',
    'api_settings': 'এপিআই সেটিংস',
    'change_api_key': 'এপিআই কী পরিবর্তন করুন',
    'api_key_notice': 'এই কীটি স্মার্ট বর্ণনা এবং সার্চ রিকমেন্ডেশনের মতো এআই ফিচারের জন্য ব্যবহৃত হয়।',
    'custom_api_key': 'কাস্টম এপিআই কী',
    'save_api_key': 'এপিআই কী সেভ করুন',
    'api_key_saved': 'এপিআই কী সফলভাবে সেভ করা হয়েছে!',
    'twelvedata_api_key': 'টুয়েলভডেটা এপিআই কী',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('shopbd_lang');
    return (saved === 'bn' || saved === 'en') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('shopbd_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
